// src/components/ai/DailyBriefing.tsx
import React, { useState, useEffect } from 'react';
import { 
  Sun, 
  TrendingUp, 
  Target, 
  AlertTriangle, 
  CheckCircle, 
  Clock, 
  Brain,
  RefreshCw,
  Loader2
} from 'lucide-react';
import type { AgentInsight, AgentAction } from '../../lib/intelligence/meshos-ai-agent';

interface DailyBriefingData {
  briefing: string;
  insights: AgentInsight[];
  actions: AgentAction[];
  focus: string;
  timestamp: string;
}

interface DailyBriefingProps {
  className?: string;
}

export default function DailyBriefing({ className = '' }: DailyBriefingProps) {
  const [briefingData, setBriefingData] = useState<DailyBriefingData | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchBriefing = async () => {
    setIsLoading(true);
    setError(null);
    
    try {
      const response = await fetch('/api/ai/daily-briefing');
      const data = await response.json();
      
      if (data.success) {
        setBriefingData(data);
      } else {
        throw new Error(data.error || 'Failed to fetch briefing');
      }
    } catch (err) {
      console.error('Briefing fetch error:', err);
      setError(err instanceof Error ? err.message : 'Failed to load briefing');
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchBriefing();
  }, []);

  const getTimeGreeting = () => {
    const hour = new Date().getHours();
    if (hour < 12) return 'Good morning';
    if (hour < 17) return 'Good afternoon';
    return 'Good evening';
  };

  const getInsightIcon = (type: string) => {
    switch (type) {
      case 'habit':
        return <Target className="w-5 h-5" />;
      case 'health':
        return <Brain className="w-5 h-5" />;
      case 'finance':
        return <TrendingUp className="w-5 h-5" />;
      case 'correlation':
        return <Brain className="w-5 h-5" />;
      default:
        return <AlertTriangle className="w-5 h-5" />;
    }
  };

  const getImpactColor = (impact: string) => {
    switch (impact) {
      case 'high':
        return 'border-red-200 bg-red-50 text-red-800';
      case 'medium':
        return 'border-yellow-200 bg-yellow-50 text-yellow-800';
      case 'low':
        return 'border-green-200 bg-green-50 text-green-800';
      default:
        return 'border-gray-200 bg-gray-50 text-gray-800';
    }
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'high':
        return 'border-red-200 bg-red-50';
      case 'medium':
        return 'border-yellow-200 bg-yellow-50';
      case 'low':
        return 'border-green-200 bg-green-50';
      default:
        return 'border-gray-200 bg-gray-50';
    }
  };

  if (isLoading) {
    return (
      <div className={`bg-white rounded-lg shadow-lg p-6 ${className}`}>
        <div className="flex items-center justify-center h-64">
          <div className="text-center">
            <Loader2 className="w-8 h-8 animate-spin text-blue-500 mx-auto mb-4" />
            <p className="text-gray-600">Mesh is preparing your daily briefing...</p>
          </div>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className={`bg-white rounded-lg shadow-lg p-6 ${className}`}>
        <div className="text-center">
          <AlertTriangle className="w-12 h-12 text-red-500 mx-auto mb-4" />
          <h3 className="text-lg font-semibold text-gray-900 mb-2">Unable to Load Briefing</h3>
          <p className="text-gray-600 mb-4">{error}</p>
          <button
            onClick={fetchBriefing}
            className="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-lg transition-colors flex items-center gap-2 mx-auto"
          >
            <RefreshCw className="w-4 h-4" />
            Try Again
          </button>
        </div>
      </div>
    );
  }

  if (!briefingData) {
    return null;
  }

  return (
    <div className={`bg-gradient-to-br from-blue-50 to-purple-50 rounded-lg shadow-lg ${className}`}>
      {/* Header */}
      <div className="p-6 border-b border-gray-200">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 bg-gradient-to-r from-blue-500 to-purple-600 rounded-full flex items-center justify-center">
              <Sun className="w-6 h-6 text-white" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-gray-900">
                {getTimeGreeting()}! Here's your daily briefing
              </h2>
              <p className="text-sm text-gray-600">
                Generated by Mesh • {new Date(briefingData.timestamp).toLocaleString()}
              </p>
            </div>
          </div>
          <button
            onClick={fetchBriefing}
            className="p-2 text-gray-500 hover:text-gray-700 hover:bg-white rounded-lg transition-colors"
            title="Refresh briefing"
          >
            <RefreshCw className="w-5 h-5" />
          </button>
        </div>
      </div>

      <div className="p-6 space-y-6">
        {/* Main Briefing */}
        <div className="bg-white rounded-lg p-4 shadow-sm">
          <div className="flex items-center gap-2 mb-3">
            <Brain className="w-5 h-5 text-blue-600" />
            <h3 className="font-semibold text-gray-900">Your Daily Overview</h3>
          </div>
          <div className="prose prose-sm max-w-none text-gray-700">
            {briefingData.briefing.split('\n').map((paragraph, index) => (
              <p key={index} className="mb-2 last:mb-0">
                {paragraph}
              </p>
            ))}
          </div>
        </div>

        {/* Today's Focus */}
        <div className="bg-white rounded-lg p-4 shadow-sm border-l-4 border-blue-500">
          <div className="flex items-center gap-2 mb-2">
            <Target className="w-5 h-5 text-blue-600" />
            <h3 className="font-semibold text-gray-900">Today's Focus</h3>
          </div>
          <p className="text-gray-700 font-medium">{briefingData.focus}</p>
        </div>

        {/* Key Insights */}
        {briefingData.insights.length > 0 && (
          <div className="bg-white rounded-lg p-4 shadow-sm">
            <h3 className="font-semibold text-gray-900 mb-4 flex items-center gap-2">
              <TrendingUp className="w-5 h-5 text-green-600" />
              Key Insights
            </h3>
            <div className="space-y-3">
              {briefingData.insights.slice(0, 4).map((insight) => (
                <div
                  key={insight.id}
                  className={`border rounded-lg p-3 ${getImpactColor(insight.impact)}`}
                >
                  <div className="flex items-start gap-3">
                    <div className="flex-shrink-0 mt-0.5">
                      {getInsightIcon(insight.type)}
                    </div>
                    <div className="flex-1">
                      <h4 className="font-medium text-sm mb-1">{insight.title}</h4>
                      <p className="text-sm opacity-90">{insight.description}</p>
                      <div className="flex items-center gap-3 mt-2">
                        <span className="text-xs font-medium">
                          {insight.impact} impact
                        </span>
                        <span className="text-xs opacity-75">
                          {Math.round(insight.confidence * 100)}% confidence
                        </span>
                        <span className="text-xs opacity-75 capitalize">
                          {insight.urgency} urgency
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Today's Actions */}
        {briefingData.actions.length > 0 && (
          <div className="bg-white rounded-lg p-4 shadow-sm">
            <h3 className="font-semibold text-gray-900 mb-4 flex items-center gap-2">
              <CheckCircle className="w-5 h-5 text-blue-600" />
              Recommended Actions
            </h3>
            <div className="space-y-3">
              {briefingData.actions.slice(0, 4).map((action) => (
                <div
                  key={action.id}
                  className={`border rounded-lg p-3 ${getPriorityColor(action.priority)}`}
                >
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <div className="flex items-center gap-2 mb-1">
                        <h4 className="font-medium text-sm">{action.title}</h4>
                        {action.automated && (
                          <span className="text-xs bg-green-100 text-green-700 px-2 py-1 rounded-full">
                            Auto
                          </span>
                        )}
                      </div>
                      <p className="text-sm text-gray-700 mb-2">{action.description}</p>
                      <div className="flex items-center gap-3">
                        <span className="text-xs font-medium text-gray-600 flex items-center gap-1">
                          <Clock className="w-3 h-3" />
                          {action.timing}
                        </span>
                        <span className="text-xs font-medium text-gray-600 capitalize">
                          {action.priority} priority
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Quick Stats */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div className="bg-white rounded-lg p-4 text-center shadow-sm">
            <div className="text-2xl font-bold text-blue-600">{briefingData.insights.length}</div>
            <div className="text-sm text-gray-600">Insights</div>
          </div>
          <div className="bg-white rounded-lg p-4 text-center shadow-sm">
            <div className="text-2xl font-bold text-green-600">{briefingData.actions.length}</div>
            <div className="text-sm text-gray-600">Actions</div>
          </div>
          <div className="bg-white rounded-lg p-4 text-center shadow-sm">
            <div className="text-2xl font-bold text-purple-600">
              {briefingData.insights.filter(i => i.impact === 'high').length}
            </div>
            <div className="text-sm text-gray-600">High Impact</div>
          </div>
          <div className="bg-white rounded-lg p-4 text-center shadow-sm">
            <div className="text-2xl font-bold text-orange-600">
              {briefingData.actions.filter(a => a.timing === 'immediate').length}
            </div>
            <div className="text-sm text-gray-600">Immediate</div>
          </div>
        </div>
      </div>
    </div>
  );
}